# Generated by Django 5.1.7 on 2025-03-15 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255)),
                ('meta_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('category_title', models.CharField(max_length=255)),
                ('category_desc', models.TextField(blank=True, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='categories/images/')),
                ('category_image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order_number', models.IntegerField(default=0)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255)),
                ('meta_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('product_title', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100)),
                ('fluidlok_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('choose_either', models.CharField(choices=[('link', 'Link'), ('document', 'Document')], default='link', max_length=10)),
                ('fluidlok_information', models.TextField(blank=True, null=True)),
                ('fluidlok_image', models.ImageField(blank=True, null=True, upload_to='products/fluidlok/')),
                ('fluidlok_image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_features', models.TextField(blank=True, null=True)),
                ('product_specification', models.TextField(blank=True, null=True)),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('product_image1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('product_image2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_large_image', models.ImageField(blank=True, null=True, upload_to='products/large_images/')),
                ('sort_order_number', models.IntegerField(default=0)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('coming_soon', models.BooleanField(default=False)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
    ]
