# Generated by Django 5.1.7 on 2025-03-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order_number', 'category_title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_category', 'sort_order_number', 'product_title'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
