# Generated by Django 5.1.7 on 2025-03-13 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='events/images/')),
                ('image_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('exhibition_name', models.CharField(max_length=255)),
                ('booth_number', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=100)),
                ('hall_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='news/images/')),
                ('image_name', models.CharField(max_length=255)),
                ('inner_image', models.ImageField(blank=True, null=True, upload_to='news/inner_images/')),
                ('inner_image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='blogs.newscategory')),
            ],
        ),
    ]
